import component from "./tests/component";
import data from "./tests/data";
import lifecycle from "./tests/lifecycle";
import prop from "./tests/prop";
import render from "./tests/render";
import watch from "./tests/watch";
import on from "./tests/on";
import emit from "./tests/emit";
import methods from "./tests/methods";
import computed from "./tests/computed";
component();
data();
lifecycle();
prop();
render();
watch();
on();
emit();
methods();
computed();